"""Generate FreeRADIUS clients.conf from NAS client records."""

from app.models.nas_client import NASClient
from app.utils.encryption import decrypt_secret


def generate_clients_conf(clients: list[NASClient]) -> str:
    """Generate clients.conf content from a list of NAS clients."""
    lines = [
        "# FreeRADIUS clients configuration",
        "# Auto-generated by RADIUS Manager Web UI",
        f"# Total clients: {len(clients)}",
        f"# Generated at: {__import__('datetime').datetime.now()}",
        "",
        "# Localhost (always present)",
        "client localhost {",
        "    ipaddr = 127.0.0.1",
        "    secret = testing123",
        "    require_message_authenticator = no",
        "    nas_type = other",
        "}",
        "",
    ]

    for client in clients:
        if not client.enabled:
            continue

        decrypted_secret = decrypt_secret(client.secret)

        lines.append(f"client {client.shortname} {{")
        lines.append(f"    ipaddr = {client.ip_address}")
        lines.append(f"    secret = {decrypted_secret}")
        lines.append(f"    nas_type = {client.nas_type}")
        if client.description:
            lines.append(f"    # {client.description}")
        lines.append("}")
        lines.append("")

    return "\n".join(lines)
